default[:amq][:user]	 = 'appa'
default[:amq][:home]  	 = '/usr/local/jboss-a-mq'
default[:amq][:install]  = '/usr/local/jboss-a-mq-6.0.0.redhat-024'
default[:amq][:file]     = 'jboss-a-mq-6.0.0.redhat-024.tar.gz'
default[:amq][:url]      = 'xxxx'